apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-job-every-15-mins
spec:
  schedule: "0,2,4 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - image: luksa/batch-job
            name: main
