apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: kubia-app
    spec:
      containers:
      - name: kubia
        image: tideorz/kubia
        ports:
        - containerPort: 8080

  
